### ISSUE TITLE
Uniqueness validation of ARM does not understand soft deletes

### ISSUE THREAD

**Issue by chrisortman** [sparc-request/sparc-fulfillment#270]
ARM has a unique validation on the name attribute, but the validate uniqueness of check does not seem to be respecting the soft deleted rows.
If an arm is soft deleted it will still prevent you from creating an arm with that name.

**Comment by Stuart-Johnson** [comment]
I've looked into this, and this doesn't seem to be the case. I created an arm, deleted it, and was able to create another one with the same name right after. This behavior follows what the documentation outlines here, for the acts_as_paranoid gem we use: https://github.com/ActsAsParanoid/acts_as_paranoid#validation

Validation ignores soft-deleted records by default. This is our intended functionality.

**Comment by chrisortman** [comment]
@Stuart-Johnson You're right, it seems to have gotten fixed between 2.6.5 and 2.7.0

Thanks
